### ISSUE TITLE
ReversionMiddleware does not work with django 1.9.7

### ISSUE THREAD

**Issue by corebyte** [etianen/django-reversion#556] opened 2016-07-14 14:09 UTC
I have the following setup:
Django==1.9.7
Django-reversion==2.0.7

Added middleware to MIDDLEWARE_CLASSES.

Dit work when developed and production server great but now it doenst commit anything anymore.
When i look in the /admin/ and make a record, it says record added... but the list is empty.

When i remove ReversionMiddleware from the MIDDLEWARE_CLASSES the problem is solved...

Doe you know what the problem could be?

I use also djangorestframework and some other plugins..

**Comment by etianen** [comment] 2016-07-14 14:34
I'm afraid I can't reproduce this. I get revisions created both with and without the middleware, both in development and on a production server.

**Comment by etianen** [comment] 2016-07-21 08:21
I think that this is a duplicate of #555.

This is fixed in the master branch. I'll be releasing a new version today.

**Closed by etianen** 2016-07-21 08:21 UTC
Labels: worksforme

**Comment by etianen** [comment] 2016-07-21 08:44
Fixed in v2.0.6

**Comment by corebyte** [comment] 2016-08-24 07:16
@etianen I noticed you fixed it, but in your changelog you said problem with gunicorn, it was also a problem in my case with supervisor. But now it is indeed fixed. Great!!
