### ISSUE TITLE
Deleted history for proxy models

### ISSUE THREAD

**Issue by lpakula** [etianen/django-reversion#500] opened 2016-04-06 16:01 UTC
If there are two proxy models against the same base model, deleted history is not filtered out properly. 

All objects from proxy model 'A' appear as deleted in proxy model 'B' history page, and vice versa.

**Comment by etianen** [comment] 2016-04-07 15:07
Hmm, looks like this is a duplicate of an issue discussed in #134. We should continue the discussion there. I'll re-open #134.

**Closed by etianen** 2016-04-07 15:07 UTC
Labels: duplicate
